# Generated by Django 3.2.5 on 2024-03-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=10, choices=[('no', 'No'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French')])),
                ('alias', models.CharField(max_length=50, default="")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
