# Generated by Django 3.2.5 on 2024-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('no', 'No'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='no', max_length=10),
        ),
        
        migrations.AlterField(
            model_name='usersettings',
            name='alias',
            field=models.CharField(max_length=50, default=''),  # Define el valor predeterminado como una cadena vacía
        ),
    ]
