# Generated by Django 3.2.5 on 2024-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador1_nombre', models.CharField(default='', max_length=150)),
                ('jugador2_nombre', models.CharField(default='', max_length=150)),
                ('empezado', models.BooleanField(default=False)),
                ('terminado', models.BooleanField(default=False)),
                ('comienzo', models.DateTimeField(blank=True, default=None, null=True)),
                ('fin', models.DateTimeField(blank=True, default=None, null=True)),
                ('desconectado', models.BooleanField(default=False)),
                ('jugador1_marcador', models.IntegerField(default=0)),
                ('jugador2_marcador', models.IntegerField(default=0)),
                ('pausa', models.BooleanField(default=False)),
                ('finDePausa', models.DateTimeField(blank=True, default=None, null=True)),
                ('pelota_actualizacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('pelota_x', models.FloatField(default=0)),
                ('pelota_y', models.FloatField(default=0)),
                ('pelota_velocidad_x', models.FloatField(default=0)),
                ('pelota_velocidad_y', models.FloatField(default=0)),
                ('jugador1_actualizacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('jugador1_y', models.FloatField(default=0)),
                ('jugador1_velocidad_y', models.FloatField(default=0)),
                ('jugador2_actualizacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('jugador2_y', models.FloatField(default=0)),
                ('jugador2_velocidad_y', models.FloatField(default=0)),
            ],
        ),
    ]
