# Generated by Django 5.0.2 on 2024-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_partido_enjuego_estadotorneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido_enjuego',
            name='limiteTiempoConUnJugador',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
