# Generated by Django 5.0.2 on 2024-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0004_partido_enjuego_limitetiempoconunjugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido_historia',
            name='partido_enJuego_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='partido_enjuego',
            name='estadoTorneo',
            field=models.CharField(choices=[('0', 'Sin jugadores'), ('1', 'Jugador 1 dentro'), ('2', 'Jugador 2 dentro'), ('A', 'Ambos jugadores dentro')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='partido_enjuego',
            name='tipo',
            field=models.CharField(choices=[('R', 'Rápido'), ('T', 'Torneo')], default='R', max_length=1),
        ),
    ]
