# Generated by Django 5.0.2 on 2024-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0005_partido_historia_partido_enjuego_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido_enjuego',
            name='rearranque',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
