# Generated by Django 3.2.5 on 2024-02-23 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150)),
                ('comienzo_inscripcion', models.DateTimeField(blank=True, default=None, null=True)),
                ('fin_inscripcion', models.DateTimeField(blank=True, default=None, null=True)),
                ('comienzo_partidos', models.DateTimeField(blank=True, default=None, null=True)),
                ('minutos_entre_partidos', models.IntegerField(default=30)),
                ('users', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
