# Generated by Django 3.2.5 on 2024-02-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='users',
            new_name='jugadores',
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torneo',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FaseTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.IntegerField(default=0)),
                ('lista_partidos', models.TextField(default='')),
                ('lista_partidos_resultados', models.TextField(default='')),
                ('lista_partidos_resultados_alias', models.TextField(default='')),
                ('ganadores', models.ManyToManyField(blank=True, default=None, related_name='ft_users_ganadores', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, default=None, related_name='ft_users_jugadores', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo')),
            ],
        ),
    ]
