# Generated by Django 5.0.2 on 2024-03-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_auto_20240226_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fasetorneo',
            unique_together={('torneo', 'fase')},
        ),
    ]
