# Generated by Django 5.0.2 on 2024-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_alter_fasetorneo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='minutos_duracion_maxima_partidos',
            field=models.IntegerField(default=15),
        ),
    ]
