# Generated by Django 5.0.2 on 2024-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_torneo_minutos_duracion_maxima_partidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasetorneo',
            name='jugadores',
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='lista_jugadores',
            field=models.TextField(default=''),
        ),
    ]
